import { generalSettings } from "./general.js";
import { buildGroups } from "./group-catalog.js";
import { parseOptions } from "./options.js";
import { renderGroups } from "./render-groups.js";
import { renderRules, ruleBaseUrlForChannel } from "./render-rules.js";
import { nodeMetadata } from "../../../shared/contracts.js";

const NODE_REFRESH_SECONDS = 21600;
const RULE_REFRESH_SECONDS = 86400;

/**
 * Compose the complete Shadowrocket Profile. Node transport data deliberately
 * never crosses this boundary: group selection is based only on inventory
 * metadata consumed by buildGroups.
 */
export function renderProfile(rawOptions, nodes, { ruleBaseUrl } = {}) {
  const options = parseOptions(rawOptions);
  const inventory = Array.isArray(nodes) ? nodes : [];
  const hasChainedNodes = inventory.some((node) => nodeMetadata(node).chained === true);
  const hasEligibleEntry = inventory.some((node) => nodeMetadata(node).entry === true && nodeMetadata(node).chained !== true);
  if (options.clientChain === "off" && hasChainedNodes) {
    throw new Error("clientChain=off rejects an inventory containing chained nodes");
  }
  if (options.clientChain === "on" && hasChainedNodes && !hasEligibleEntry) {
    throw new Error("clientChain=on requires an eligible unchained entry for chained nodes");
  }
  const header = [
    "# Generated by shadowrocket-profile. Do not paste credentials into this file.",
    `# platform=${options.platform}; node-count=${inventory.length}; node-refresh=${NODE_REFRESH_SECONDS}; rule-refresh=${RULE_REFRESH_SECONDS}`,
  ].join("\n");
  const groups = renderGroups(buildGroups(options, inventory), options.subscriptionName).join("\n");

  return [
    header,
    `[General]\n${generalSettings(options).join("\n")}`,
    `[Proxy Group]\n${groups}`,
    `[Rule]\n${renderRules({
      ruleBaseUrl: ruleBaseUrl ?? ruleBaseUrlForChannel(options.channel),
      adblockMode: options.adblockMode,
    }).join("\n")}`,
  ].join("\n\n") + "\n";
}
