import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const comparatorUrl = new URL("../scripts/compare-baseline.mjs", import.meta.url);

// Independent compatibility expectations: intentionally not imported from the
// comparator so a literal disappearing from its runtime table still fails here.
const EXPECTED_PROFILE_OPTION_VALUES = Object.freeze({
  output: Object.freeze(["config"]),
  type: Object.freeze(["collection"]),
  platform: Object.freeze(["iphone", "ipad", "macos", "appletv"]),
  dnsMode: Object.freeze(["stable", "privacy", "speed"]),
  chinaDns: Object.freeze(["alidns", "dnspod", "system"]),
  globalDns: Object.freeze(["cloudflare", "google", "quad9"]),
  blockMode: Object.freeze(["balanced", "security", "strict", "off"]),
  quicMode: Object.freeze(["allow", "proxy-block", "all-block"]),
  ipv6Mode: Object.freeze(["auto", "ipv4-only"]),
  autoGroupMode: Object.freeze(["auto", "full", "balanced", "minimal"]),
  clientChain: Object.freeze(["off", "on"]),
});

function syntheticProfile(advertisingRule = "Advertising/Advertising.list") {
  const advertisingDomain = advertisingRule.startsWith("AdvertisingLite/")
    ? ""
    : "DOMAIN-SET,https://example.invalid/Advertising/Advertising_Domain.list,REJECT,update-interval=86400\n";
  return `# Generated by shadowrocket-profile. Do not paste credentials into this file.
# generated-at=2026-08-01T00:00:00.000Z

[General]
ipv6 = true

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https://example.invalid/ - reject

[Proxy Group]
Synthetic = select,DIRECT

[Rule]
RULE-SET,https://example.invalid/${advertisingRule},REJECT,update-interval=86400
${advertisingDomain}FINAL,Synthetic
`;
}

const ADVERTISING_LINE = "RULE-SET,https://example.invalid/Advertising/Advertising.list,REJECT,update-interval=86400";
const ADVERTISING_DOMAIN_LINE = "DOMAIN-SET,https://example.invalid/Advertising/Advertising_Domain.list,REJECT,update-interval=86400";

function advertisingMigrationMutations(current) {
  return [
    ["Advertising policy", current.replace(ADVERTISING_LINE, ADVERTISING_LINE.replace(",REJECT,", ",DIRECT,"))],
    ["Advertising interval", current.replace(ADVERTISING_LINE, ADVERTISING_LINE.replace("86400", "3600"))],
    ["Advertising URL", current.replace("Advertising/Advertising.list", "Advertising/Advertising.list?variant=changed")],
    ["Advertising_Domain policy", current.replace(ADVERTISING_DOMAIN_LINE, ADVERTISING_DOMAIN_LINE.replace(",REJECT,", ",DIRECT,"))],
    ["Advertising_Domain interval", current.replace(ADVERTISING_DOMAIN_LINE, ADVERTISING_DOMAIN_LINE.replace("86400", "3600"))],
    ["Advertising_Domain URL", current.replace("Advertising/Advertising_Domain.list", "Advertising/Advertising_Domain.list?variant=changed")],
    ["duplicate Advertising_Domain", current.replace(ADVERTISING_DOMAIN_LINE, `${ADVERTISING_DOMAIN_LINE}\n${ADVERTISING_DOMAIN_LINE}`)],
    ["non-adjacent Advertising pair", current.replace(
      `${ADVERTISING_LINE}\n${ADVERTISING_DOMAIN_LINE}`,
      `${ADVERTISING_LINE}\nDOMAIN,interstitial.example,DIRECT\n${ADVERTISING_DOMAIN_LINE}`,
    )],
    ["moved Advertising_Domain", current
      .replace(`${ADVERTISING_DOMAIN_LINE}\n`, "")
      .replace("FINAL,Synthetic", `FINAL,Synthetic\n${ADVERTISING_DOMAIN_LINE}`)],
    ["reordered Advertising pair", current.replace(
      `${ADVERTISING_LINE}\n${ADVERTISING_DOMAIN_LINE}`,
      `${ADVERTISING_DOMAIN_LINE}\n${ADVERTISING_LINE}`,
    )],
    ["missing Advertising_Domain", current.replace(`${ADVERTISING_DOMAIN_LINE}\n`, "")],
  ];
}

function syntheticNodeBundle({
  globalName = "ShadowrocketNodeBundle",
  wrapperParameters = "proxies, targetPlatform",
  rejectValidArguments = false,
  acceptUnknownArguments = false,
  acceptInvalidOutput = false,
  returnObject = false,
  extraPublicField = false,
  extraUnderscoreField = false,
  extraUnderscoreValue = true,
  structuredCloneExtraArgument = false,
  realmOwnedArray = false,
  privateMetadataName = "_profile",
  privateId = "baseline-private-id",
  privateContinent = "asiaPacific",
  loggerMethod = "info",
  loggerMessage = "synthetic diagnostics",
  loggerCount = 1,
  escapeHost = false,
  hangMode = "",
  rejectClientChainValue = "",
  coerceRawArguments = false,
  returnedName = "",
  returnedServer = "",
  returnedPort = null,
  returnedCredential = "",
} = {}) {
  return `
var ${globalName} = {
  async operator(proxies = [], targetPlatform, context = {}) {
    void targetPlatform;
    let args = context.arguments;
    if ((!args || typeof args !== "object" || Array.isArray(args)) && ${coerceRawArguments ? "true" : "false"}) args = { output: "nodes" };
    if (!args || typeof args !== "object" || Array.isArray(args)) throw new Error("arguments must be an object");
    if (${rejectValidArguments ? "true" : "false"} && args.output === "nodes") throw new Error("synthetic valid rejection");
    for (const key of Object.keys(args)) {
      if (!key.startsWith("_") && !["output", "clientChain"].includes(key) && !${acceptUnknownArguments ? "true" : "false"}) {
        throw new Error(\`Unknown option: \${key}\`);
      }
    }
    if (args.output !== "nodes" && !(${acceptInvalidOutput ? "true" : "false"} && args.output === "config")) throw new Error("output must be nodes");
    const clientChain = Object.hasOwn(args, "clientChain") ? args.clientChain : "off";
    if (clientChain !== "off" && clientChain !== "on") throw new Error("clientChain must be off or on");
    if (clientChain === ${JSON.stringify(rejectClientChainValue)}) throw new Error("synthetic removed clientChain value");
    if (${hangMode === "sync" ? "true" : "false"}) while (true) {}
    if (${hangMode === "async" ? "true" : "false"}) await new Promise(() => {});
    if (${escapeHost ? "true" : "false"}) context.logger.info.constructor("return process")();
    for (let index = 0; index < ${loggerCount}; index += 1) context.logger[${JSON.stringify(loggerMethod)}](${JSON.stringify(loggerMessage)});
    const clonedProxies = structuredClone(proxies${structuredCloneExtraArgument ? ", \"synthetic-extra\"" : ""});
    const result = clonedProxies.map((proxy) => ({
      ...proxy,
      ${returnedName ? `name: ${JSON.stringify(returnedName)},` : ""}
      ${returnedServer ? `server: ${JSON.stringify(returnedServer)},` : ""}
      ${returnedPort !== null ? `port: ${JSON.stringify(returnedPort)},` : ""}
      ${returnedCredential ? `[${JSON.stringify("password")}]: ${JSON.stringify(returnedCredential)},` : ""}
      ${extraPublicField ? "compatibilityChanged: true," : ""}
      ${extraUnderscoreField ? `_compatibilityChanged: ${JSON.stringify(extraUnderscoreValue)},` : ""}
      ${privateMetadataName}: {
        id: ${JSON.stringify(privateId)},
        sourceKind: "airport",
        continent: ${JSON.stringify(privateContinent)},
      },
    }));
    return ${returnObject ? "{ nodes: result }" : realmOwnedArray ? "Array.from(result)" : "result"};
  },
};
async function operator(${wrapperParameters}) {
  return ${globalName}.operator(proxies, typeof targetPlatform === "undefined" ? undefined : targetPlatform, {
    arguments: $arguments,
    logger: console,
  });
}
`;
}

function syntheticProfileBundle({
  globalName = "ShadowrocketProfileBundle",
  wrapperParameters = "input, targetPlatform",
  rejectValidArguments = false,
  acceptUnknownArguments = false,
  acceptInvalidKey = "",
  acceptMissingKey = "",
  rejectAcceptedKey = "",
  rejectAcceptedValue = "",
  artifactPlatform = "JSON",
  artifactCallCount = 1,
  artifactExtraArgument = false,
  extraPublicField = false,
  coerceRawArguments = false,
  acceptPrimitiveKey = "",
  acceptArrayKey = "",
  rejectTrimmedKey = "",
  rejectCrlfName = false,
  profileContent = "synthetic-profile",
} = {}) {
  return `
var ${globalName} = {
  async operator(input, targetPlatform, context = {}) {
    void targetPlatform;
    let args = context.arguments;
    if ((!args || typeof args !== "object" || Array.isArray(args)) && ${coerceRawArguments ? "true" : "false"}) args = {
      output: "config", type: "collection", name: "synthetic-collection", subscriptionName: "Synthetic-Nodes", platform: "macos"
    };
    if (!args || typeof args !== "object" || Array.isArray(args)) throw new TypeError("Options must be an object");
    const allowed = ["output", "type", "name", "subscriptionName", "platform", "dnsMode", "chinaDns", "globalDns", "blockMode", "quicMode", "ipv6Mode", "autoGroupMode", "clientChain"];
    for (const key of Object.keys(args)) {
      if (!key.startsWith("_") && !allowed.includes(key) && !${acceptUnknownArguments ? "true" : "false"}) throw new Error(\`Unknown option: \${key}\`);
    }
    if (${rejectValidArguments ? "true" : "false"} && args.output === "config" && !Object.hasOwn(args, "unknown")) throw new Error("synthetic valid rejection");
    const defaults = {
      output: "config",
      type: "collection",
      name: "synthetic-collection",
      subscriptionName: "Synthetic-Nodes",
      platform: "macos",
      dnsMode: "stable",
      chinaDns: "alidns",
      globalDns: "cloudflare",
      blockMode: "balanced",
      quicMode: "proxy-block",
      ipv6Mode: "auto",
      autoGroupMode: "auto",
      clientChain: "off",
    };
    const required = ["output", "type", "name", "subscriptionName", "platform"];
    for (const key of required) {
      if (!Object.hasOwn(args, key) && key !== ${JSON.stringify(acceptMissingKey)}) throw new Error(\`missing \${key}\`);
    }
    const values = { ...defaults, ...args };
    const accepted = {
      output: ["config"],
      type: ["collection"],
      platform: ["iphone", "ipad", "macos", "appletv"],
      dnsMode: ["stable", "privacy", "speed"],
      chinaDns: ["alidns", "dnspod", "system"],
      globalDns: ["cloudflare", "google", "quad9"],
      blockMode: ["balanced", "security", "strict", "off"],
      quicMode: ["allow", "proxy-block", "all-block"],
      ipv6Mode: ["auto", "ipv4-only"],
      autoGroupMode: ["auto", "full", "balanced", "minimal"],
      clientChain: ["off", "on"],
    };
    const acceptsSyntheticInvalidValue = (key, value) =>
      (key === ${JSON.stringify(acceptPrimitiveKey)} && value === false) ||
      (key === ${JSON.stringify(acceptArrayKey)} && Array.isArray(value));
    if (Object.hasOwn(values, ${JSON.stringify(rejectTrimmedKey)}) &&
        typeof values[${JSON.stringify(rejectTrimmedKey)}] === "string" &&
        values[${JSON.stringify(rejectTrimmedKey)}].trim() !== values[${JSON.stringify(rejectTrimmedKey)}]) {
      throw new Error("synthetic trimming removed");
    }
    for (const key of [...Object.keys(accepted), "name"]) {
      if (typeof values[key] === "string") values[key] = values[key].trim();
    }
    for (const [key, allowedValues] of Object.entries(accepted)) {
      if (key !== ${JSON.stringify(acceptInvalidKey)} && !acceptsSyntheticInvalidValue(key, values[key]) && !allowedValues.includes(values[key])) throw new Error(\`invalid \${key}\`);
    }
    for (const key of ["name", "subscriptionName"]) {
      if (key !== ${JSON.stringify(acceptInvalidKey)} && !acceptsSyntheticInvalidValue(key, values[key]) && (typeof values[key] !== "string" || !values[key])) throw new Error(\`invalid \${key}\`);
    }
    if (${JSON.stringify(acceptInvalidKey)} !== "subscriptionName" && !acceptsSyntheticInvalidValue("subscriptionName", values.subscriptionName) && (values.subscriptionName.trim() !== values.subscriptionName || /[\\r\\n]/.test(values.subscriptionName))) throw new Error("invalid subscriptionName");
    if (${rejectCrlfName ? "true" : "false"} && /[\\r\\n]/.test(values.name)) throw new Error("synthetic CRLF name rejection");
    if (values[${JSON.stringify(rejectAcceptedKey)}] === ${JSON.stringify(rejectAcceptedValue)}) throw new Error("synthetic removed accepted value");
    if (typeof context.produceArtifact !== "function") throw new Error("produceArtifact is unavailable");
    let nodes;
    for (let index = 0; index < ${artifactCallCount}; index += 1) {
      nodes = await context.produceArtifact({
        type: values.type,
        name: values.name,
        platform: ${JSON.stringify(artifactPlatform)},
        produceType: "internal",
      }${artifactExtraArgument ? ", \"synthetic-extra\"" : ""});
    }
    if (!Array.isArray(nodes) || nodes.length === 0) throw new Error("produceArtifact must return a non-empty node array");
    return { ...input, $content: ${JSON.stringify(profileContent)}${extraPublicField ? ", compatibilityChanged: true" : ""} };
  },
};
async function operator(${wrapperParameters}) {
  return ${globalName}.operator(input, typeof targetPlatform === "undefined" ? undefined : targetPlatform, {
    arguments: $arguments,
    produceArtifact,
    logger: console,
  });
}
`;
}

for (const platform of ["macos", "iphone", "ipad"]) {
  test(`${platform} example contains the layered continent selectors`, async () => {
    const profile = await readFile(new URL(`../examples/shadowrocket-${platform}.conf`, import.meta.url), "utf8");
    assert.match(profile, /^🌎 美洲 = select,/m);
    assert.match(profile, /^🚀 节点选择 = select,PROXY,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\(\?!🔗 \)\.\+\$$/m);
    assert.match(profile, /^🤖 AI 专用 = select,🤖 AI 亚太,🤖 AI 欧洲,🤖 AI 美洲,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$$/m);
    assert.match(profile, /^🤖 AI 亚太 = select,.*Shadowrocket-Nodes,use=true,.*hidden=1$/m);
    assert.match(profile, /^🐙 GitHub = select,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲,DIRECT,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$,policy-select-name=🚀 节点选择$/m);
    assert.match(profile, /^🍎 Apple = select,DIRECT,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$,policy-select-name=DIRECT$/m);
    assert.doesNotMatch(profile, /include-all-proxies=true/);
    assert.match(profile, /edge\/shadowrocket\/rules\/ByteDance\.list,🇨🇳 国内平台/);
    assert.doesNotMatch(profile, /\/(?:Advertising|Advertising_Domain|ChinaMax_Domain|ChinaMax|Game)\.list/);
    assert.match(profile, /^🇨🇳 国内平台 = select,DIRECT,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲/m);
    assert.match(profile, /^RULE-SET,.*\/DomesticCore\.list,DIRECT,/m);
    assert.match(profile, /^RULE-SET,.*\/DomesticGame\.list,DIRECT,/m);
    assert.match(profile, /^RULE-SET,.*\/SteamCN\.list,DIRECT,/m);
    assert.match(profile, /^RULE-SET,.*\/OverseasGame\.list,🌍 海外游戏,/m);
    assert.match(profile, /^RULE-SET,.*\/ChinaIP\.list,DIRECT,/m);
    assert.match(profile, /^GEOIP,CN,DIRECT$/m);
    assert.match(profile, /^FINAL,🚀 节点选择$/m);
    assert.match(profile, /^block-quic = all-proxy$/m);
    assert.match(profile, new RegExp(`^ipv6 = ${platform === "macos" ? "false" : "true"}$`, "m"));
  });
}

test("profile compatibility permits only the Advertising replacement and generated timestamp", async () => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");
  const current = syntheticProfile().replace(
    "2026-08-01T00:00:00.000Z",
    "2026-08-02T12:34:56.000Z",
  );

  assert.doesNotThrow(() => compareProfileText(current, baseline, "synthetic.conf"));
  assert.doesNotThrow(() => compareProfileText(
    syntheticProfile().replace("2026-08-01T00:00:00.000Z", "2024-02-29T23:59:59.999+14:00"),
    baseline,
    "synthetic-offset.conf",
  ));
});

test("profile compatibility rejects every unapproved section and rule change", async (t) => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");
  const current = syntheticProfile();
  const hostBlock = "[Host]\nlocalhost = 127.0.0.1\n";
  const rewriteBlock = "[URL Rewrite]\n^https://example.invalid/ - reject\n";
  const mutations = [
    ["General", current.replace("ipv6 = true", "ipv6 = false")],
    ["Host", current.replace("localhost = 127.0.0.1", "localhost = ::1")],
    ["URL Rewrite", current.replace(" - reject", " - 302")],
    ["Proxy Group", current.replace("Synthetic = select,DIRECT", "Synthetic = select,REJECT")],
    ["Rule", current.replace("FINAL,Synthetic", "FINAL,DIRECT")],
    ["non-timestamp header value", current.replace("2026-08-01T00:00:00.000Z", "not-a-timestamp")],
    ["impossible calendar date", current.replace("2026-08-01T00:00:00.000Z", "2026-02-30T00:00:00.000Z")],
    ["impossible non-leap date", current.replace("2026-08-01T00:00:00.000Z", "2026-02-29T00:00:00.000Z")],
    ["impossible hour", current.replace("2026-08-01T00:00:00.000Z", "2026-08-01T24:00:00.000Z")],
    ["impossible minute", current.replace("2026-08-01T00:00:00.000Z", "2026-08-01T00:60:00.000Z")],
    ["impossible second", current.replace("2026-08-01T00:00:00.000Z", "2026-08-01T00:00:60.000Z")],
    ["impossible offset", current.replace("2026-08-01T00:00:00.000Z", "2026-08-01T00:00:00.000+15:00")],
    ["impossible maximum offset minutes", current.replace("2026-08-01T00:00:00.000Z", "2026-08-01T00:00:00.000+14:30")],
    ["additional section", `${current}\n[MITM]\nenable = true\n`],
    ["section order", current.replace("[Host]", "[Host Renamed]")],
    ["true section reorder", current.replace(`${hostBlock}\n${rewriteBlock}`, `${rewriteBlock}\n${hostBlock}`)],
    ["missing section", current.replace(`${hostBlock}\n`, "")],
  ];

  for (const [name, mutation] of mutations) {
    await t.test(name, () => {
      assert.throws(() => compareProfileText(mutation, baseline, "synthetic.conf"));
    });
  }
});

test("profile compatibility requires the approved Advertising replacement", async () => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");

  assert.throws(
    () => compareProfileText(baseline, baseline, "synthetic.conf"),
    /approved Advertising replacement/,
  );
  for (const [name, mutation] of advertisingMigrationMutations(syntheticProfile())) {
    assert.throws(
      () => compareProfileText(mutation, baseline, "synthetic.conf"),
      undefined,
      name,
    );
  }
});

test("bundle compatibility permits only the exact full Advertising expansion", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const baseline = syntheticProfileBundle({
    profileContent: syntheticProfile("AdvertisingLite/AdvertisingLite.list"),
  });
  const current = syntheticProfile();

  await assert.doesNotReject(() => compareBundleSources(
    "profile",
    syntheticProfileBundle({ profileContent: current }),
    baseline,
    "synthetic-profile-advertising.js",
  ));
  for (const [name, mutation] of advertisingMigrationMutations(current)) {
    await t.test(name, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ profileContent: mutation }),
        baseline,
        "synthetic-profile-advertising.js",
      ));
    });
  }
});

test("bundle compatibility ignores private IDs and rejects public contract changes", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const current = syntheticNodeBundle({
    privateId: "rebuilt-private-id",
    privateMetadataName: "_profile",
    realmOwnedArray: true,
  });
  const baseline = syntheticNodeBundle({
    privateId: "legacy-private-id",
    privateMetadataName: "_sr",
    realmOwnedArray: true,
  });

  await assert.doesNotReject(() => compareBundleSources("node", current, baseline, "synthetic-node.js"));
  await assert.doesNotReject(() => compareBundleSources(
    "node",
    syntheticNodeBundle({ privateId: "current-only-id" }),
    syntheticNodeBundle({ privateId: "baseline-only-id" }),
    "synthetic-id-only.js",
  ));
  await assert.doesNotReject(() => compareBundleSources(
    "node",
    syntheticNodeBundle({ privateMetadataName: "_profile", privateId: "same-id" }),
    syntheticNodeBundle({ privateMetadataName: "_sr", privateId: "same-id" }),
    "synthetic-metadata-key.js",
  ));
  await assert.rejects(() => compareBundleSources(
    "node",
    syntheticNodeBundle({ extraUnderscoreField: true, extraUnderscoreValue: false }),
    syntheticNodeBundle({ extraUnderscoreField: true, extraUnderscoreValue: true }),
    "synthetic-underscore-value.js",
  ));
  await assert.rejects(() => compareBundleSources(
    "node",
    syntheticNodeBundle({ structuredCloneExtraArgument: true }),
    syntheticNodeBundle(),
    "synthetic-structured-clone-arguments.js",
  ));

  for (const [name, mutation] of [
    ["node name", syntheticNodeBundle({ returnedName: "Changed Synthetic Node" })],
    ["node server", syntheticNodeBundle({ returnedServer: "203.0.113.99" })],
    ["node port", syntheticNodeBundle({ returnedPort: 8443 })],
    ["node password", syntheticNodeBundle({ returnedCredential: "TEST_ONLY_CHANGED_PASSWORD" })],
  ]) {
    await t.test(`changed public ${name}`, async () => {
      await assert.rejects(
        () => compareBundleSources("node", mutation, baseline, "synthetic-node.js"),
        (error) => {
          assert.doesNotMatch(error.message, /TEST_ONLY_NOT_A_SECRET|TEST_ONLY_CHANGED_PASSWORD/);
          return true;
        },
      );
    });
  }

  const mutations = [
    ["exported global name", syntheticNodeBundle({ globalName: "RenamedNodeBundle" })],
    ["operator arity", syntheticNodeBundle({ wrapperParameters: "proxies" })],
    ["accepted arguments", syntheticNodeBundle({ rejectValidArguments: true })],
    ["rejected arguments", syntheticNodeBundle({ acceptUnknownArguments: true })],
    ["invalid output value", syntheticNodeBundle({ acceptInvalidOutput: true })],
    ["returned shape", syntheticNodeBundle({ returnObject: true })],
    ["public returned field", syntheticNodeBundle({ extraPublicField: true })],
    ["private metadata value", syntheticNodeBundle({ privateContinent: "europe" })],
    ["arbitrary underscore field", syntheticNodeBundle({ extraUnderscoreField: true })],
    ["renamed private metadata", syntheticNodeBundle({ privateMetadataName: "_metadata" })],
    ["removed diagnostics logging", syntheticNodeBundle({ loggerCount: 0 })],
    ["changed diagnostics logger method", syntheticNodeBundle({ loggerMethod: "log" })],
    ["changed diagnostics logger arguments", syntheticNodeBundle({ loggerMessage: "changed diagnostics" })],
    ["changed diagnostics count", syntheticNodeBundle({ loggerCount: 2 })],
    ["removed accepted node option", syntheticNodeBundle({ rejectClientChainValue: "on" })],
    ["accepted raw arguments", syntheticNodeBundle({ coerceRawArguments: true })],
  ];

  for (const [name, mutation] of mutations) {
    await t.test(name, async () => {
      await assert.rejects(() => compareBundleSources("node", mutation, baseline, "synthetic-node.js"));
    });
  }
});

test("bundle compatibility contains VM escapes and terminates hung operators", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const baseline = syntheticNodeBundle({ privateMetadataName: "_sr" });

  await t.test("host constructor escape", async () => {
    await assert.rejects(() => compareBundleSources(
      "node",
      syntheticNodeBundle({ escapeHost: true }),
      baseline,
      "escape-node.js",
      { timeoutMs: 500 },
    ));
  });
  await t.test("synchronous infinite loop", async () => {
    await assert.rejects(
      () => compareBundleSources(
        "node",
        syntheticNodeBundle({ hangMode: "sync" }),
        baseline,
        "sync-hang-node.js",
        { timeoutMs: 500 },
      ),
      /timed out/,
    );
  });
  await t.test("never-resolving promise", async () => {
    await assert.rejects(
      () => compareBundleSources(
        "node",
        syntheticNodeBundle({ hangMode: "async" }),
        baseline,
        "async-hang-node.js",
        { timeoutMs: 500 },
      ),
      /timed out/,
    );
  });
});

test("profile bundle compatibility rejects profile-specific contract changes", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const baseline = syntheticProfileBundle();

  await assert.doesNotReject(() => compareBundleSources("profile", baseline, baseline, "synthetic-profile.js"));

  const contractMutations = [
    ["exported global name", syntheticProfileBundle({ globalName: "RenamedProfileBundle" })],
    ["operator arity", syntheticProfileBundle({ wrapperParameters: "input" })],
    ["accepted arguments", syntheticProfileBundle({ rejectValidArguments: true })],
    ["rejected arguments", syntheticProfileBundle({ acceptUnknownArguments: true })],
    ["artifact request", syntheticProfileBundle({ artifactPlatform: "YAML" })],
    ["artifact request count", syntheticProfileBundle({ artifactCallCount: 2 })],
    ["artifact extra argument", syntheticProfileBundle({ artifactExtraArgument: true })],
    ["returned shape", syntheticProfileBundle({ extraPublicField: true })],
    ["profile content", syntheticProfileBundle({ profileContent: "changed-synthetic-profile" })],
  ];
  for (const [name, mutation] of contractMutations) {
    await t.test(name, async () => {
      await assert.rejects(() => compareBundleSources("profile", mutation, baseline, "synthetic-profile.js"));
    });
  }

  for (const [key, values] of Object.entries(EXPECTED_PROFILE_OPTION_VALUES)) {
    for (const value of values) {
      await t.test(`removed accepted ${key}=${value}`, async () => {
        await assert.rejects(() => compareBundleSources(
          "profile",
          syntheticProfileBundle({ rejectAcceptedKey: key, rejectAcceptedValue: value }),
          baseline,
          "synthetic-profile.js",
        ));
      });
    }
  }

  for (const key of ["name", ...Object.keys(EXPECTED_PROFILE_OPTION_VALUES)]) {
    await t.test(`removed accepted trimming for ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ rejectTrimmedKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }

  await t.test("removed accepted CRLF collection name", async () => {
    await assert.rejects(() => compareBundleSources(
      "profile",
      syntheticProfileBundle({ rejectCrlfName: true }),
      baseline,
      "synthetic-profile.js",
    ));
  });

  await t.test("accepted raw profile arguments", async () => {
    await assert.rejects(() => compareBundleSources(
      "profile",
      syntheticProfileBundle({ coerceRawArguments: true }),
      baseline,
      "synthetic-profile.js",
    ));
  });

  for (const key of [
    "output", "type", "name", "subscriptionName", "platform", "dnsMode", "chinaDns",
    "globalDns", "blockMode", "quicMode", "ipv6Mode", "autoGroupMode", "clientChain",
  ]) {
    await t.test(`invalid ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptInvalidKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }

  for (const key of [
    "output", "type", "name", "subscriptionName", "platform", "dnsMode", "chinaDns",
    "globalDns", "blockMode", "quicMode", "ipv6Mode", "autoGroupMode", "clientChain",
  ]) {
    await t.test(`primitive ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptPrimitiveKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
    await t.test(`array ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptArrayKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }

  for (const key of ["output", "type", "name", "subscriptionName", "platform"]) {
    await t.test(`missing ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptMissingKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }
});

test("compatibility verification refuses an unavailable baseline directory", async () => {
  const { verifyCompatibility } = await import(comparatorUrl);

  await assert.rejects(
    () => verifyCompatibility({
      baselineDir: new URL("fixtures/no-such-shadowrocket-baseline", import.meta.url).pathname,
      targetDir: new URL("..", import.meta.url).pathname,
    }),
    { message: "Shadowrocket baseline directory is unavailable" },
  );
});
