import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const comparatorUrl = new URL("../scripts/compare-baseline.mjs", import.meta.url);

function syntheticProfile(advertisingRule = "Advertising/Advertising.list") {
  return `# Generated by shadowrocket-profile. Do not paste credentials into this file.
# generated-at=2026-08-01T00:00:00.000Z

[General]
ipv6 = true

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https://example.invalid/ - reject

[Proxy Group]
Synthetic = select,DIRECT

[Rule]
RULE-SET,https://example.invalid/${advertisingRule},REJECT
FINAL,Synthetic
`;
}

function syntheticNodeBundle({
  globalName = "ShadowrocketNodeBundle",
  wrapperParameters = "proxies, targetPlatform",
  rejectValidArguments = false,
  acceptUnknownArguments = false,
  acceptInvalidOutput = false,
  returnObject = false,
  extraPublicField = false,
  realmOwnedArray = false,
  privateMetadataName = "_profile",
  privateId = "baseline-private-id",
} = {}) {
  return `
var ${globalName} = {
  async operator(proxies = [], targetPlatform, context = {}) {
    void targetPlatform;
    const args = context.arguments;
    if (!args || typeof args !== "object" || Array.isArray(args)) throw new Error("arguments must be an object");
    if (${rejectValidArguments ? "true" : "false"} && args.output === "nodes") throw new Error("synthetic valid rejection");
    for (const key of Object.keys(args)) {
      if (!key.startsWith("_") && !["output", "clientChain"].includes(key) && !${acceptUnknownArguments ? "true" : "false"}) {
        throw new Error(\`Unknown option: \${key}\`);
      }
    }
    if (args.output !== "nodes" && !(${acceptInvalidOutput ? "true" : "false"} && args.output === "config")) throw new Error("output must be nodes");
    const clientChain = Object.hasOwn(args, "clientChain") ? args.clientChain : "off";
    if (clientChain !== "off" && clientChain !== "on") throw new Error("clientChain must be off or on");
    const result = proxies.map((proxy) => ({
      ...proxy,
      ${extraPublicField ? "compatibilityChanged: true," : ""}
      ${privateMetadataName}: { id: ${JSON.stringify(privateId)}, sourceKind: "airport" },
    }));
    return ${returnObject ? "{ nodes: result }" : realmOwnedArray ? "Array.from(result)" : "result"};
  },
};
async function operator(${wrapperParameters}) {
  return ${globalName}.operator(proxies, typeof targetPlatform === "undefined" ? undefined : targetPlatform, {
    arguments: $arguments,
    logger: console,
  });
}
`;
}

function syntheticProfileBundle({
  globalName = "ShadowrocketProfileBundle",
  wrapperParameters = "input, targetPlatform",
  acceptInvalidKey = "",
  acceptMissingKey = "",
  artifactPlatform = "JSON",
  extraPublicField = false,
} = {}) {
  return `
var ${globalName} = {
  async operator(input, targetPlatform, context = {}) {
    void targetPlatform;
    const args = context.arguments;
    if (!args || typeof args !== "object" || Array.isArray(args)) throw new TypeError("Options must be an object");
    const allowed = ["output", "type", "name", "subscriptionName", "platform", "dnsMode", "chinaDns", "globalDns", "blockMode", "quicMode", "ipv6Mode", "autoGroupMode", "clientChain"];
    for (const key of Object.keys(args)) {
      if (!key.startsWith("_") && !allowed.includes(key)) throw new Error(\`Unknown option: \${key}\`);
    }
    const defaults = {
      output: "config",
      type: "collection",
      name: "synthetic-collection",
      subscriptionName: "Synthetic-Nodes",
      platform: "macos",
      dnsMode: "stable",
      chinaDns: "alidns",
      globalDns: "cloudflare",
      blockMode: "balanced",
      quicMode: "proxy-block",
      ipv6Mode: "auto",
      autoGroupMode: "auto",
      clientChain: "off",
    };
    const required = ["output", "type", "name", "subscriptionName", "platform"];
    for (const key of required) {
      if (!Object.hasOwn(args, key) && key !== ${JSON.stringify(acceptMissingKey)}) throw new Error(\`missing \${key}\`);
    }
    const values = { ...defaults, ...args };
    const accepted = {
      output: ["config"],
      type: ["collection"],
      platform: ["iphone", "ipad", "macos", "appletv"],
      dnsMode: ["stable", "privacy", "speed"],
      chinaDns: ["alidns", "dnspod", "system"],
      globalDns: ["cloudflare", "google", "quad9"],
      blockMode: ["balanced", "security", "strict", "off"],
      quicMode: ["allow", "proxy-block", "all-block"],
      ipv6Mode: ["auto", "ipv4-only"],
      autoGroupMode: ["auto", "full", "balanced", "minimal"],
      clientChain: ["off", "on"],
    };
    for (const [key, allowedValues] of Object.entries(accepted)) {
      if (key !== ${JSON.stringify(acceptInvalidKey)} && !allowedValues.includes(values[key])) throw new Error(\`invalid \${key}\`);
    }
    for (const key of ["name", "subscriptionName"]) {
      if (key !== ${JSON.stringify(acceptInvalidKey)} && (typeof values[key] !== "string" || !values[key])) throw new Error(\`invalid \${key}\`);
    }
    if (typeof context.produceArtifact !== "function") throw new Error("produceArtifact is unavailable");
    const nodes = await context.produceArtifact({
      type: values.type,
      name: values.name,
      platform: ${JSON.stringify(artifactPlatform)},
      produceType: "internal",
    });
    if (!Array.isArray(nodes) || nodes.length === 0) throw new Error("produceArtifact must return a non-empty node array");
    return { ...input, $content: "synthetic-profile"${extraPublicField ? ", compatibilityChanged: true" : ""} };
  },
};
async function operator(${wrapperParameters}) {
  return ${globalName}.operator(input, typeof targetPlatform === "undefined" ? undefined : targetPlatform, {
    arguments: $arguments,
    produceArtifact,
    logger: console,
  });
}
`;
}

for (const platform of ["macos", "iphone", "ipad"]) {
  test(`${platform} example contains the layered continent selectors`, async () => {
    const profile = await readFile(new URL(`../examples/shadowrocket-${platform}.conf`, import.meta.url), "utf8");
    assert.match(profile, /^🌎 美洲 = select,/m);
    assert.match(profile, /^🚀 节点选择 = select,PROXY$/m);
    assert.match(profile, /^🤖 AI 专用 = select,🤖 AI 亚太,🤖 AI 欧洲,🤖 AI 美洲,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$$/m);
    assert.match(profile, /^🤖 AI 亚太 = select,.*Shadowrocket-Nodes,use=true,.*hidden=1$/m);
    assert.match(profile, /^🐙 GitHub = select,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲,DIRECT,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$,policy-select-name=🚀 节点选择$/m);
    assert.match(profile, /^🍎 Apple = select,DIRECT,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲,Shadowrocket-Nodes,use=true,policy-regex-filter=\^\.\+\$,policy-select-name=DIRECT$/m);
    assert.doesNotMatch(profile, /include-all-proxies=true/);
    assert.match(profile, /ByteDance\/ByteDance\.list,🎵 抖音/);
    assert.match(profile, /^🎵 抖音 = select,DIRECT,🚀 节点选择,⚡ 全部自动,🛟 全部故障转移,🌏 亚太,🌍 欧洲,🌎 美洲/m);
    assert.match(profile, /^DOMAIN-SET,.*ChinaMax_Domain\.list,DIRECT,/m);
    assert.match(profile, /^DOMAIN-SUFFIX,leiting\.com,DIRECT$/m);
    assert.match(profile, /^block-quic = all-proxy$/m);
    assert.match(profile, new RegExp(`^ipv6 = ${platform === "macos" ? "false" : "true"}$`, "m"));
  });
}

test("profile compatibility permits only the Advertising replacement and generated timestamp", async () => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");
  const current = syntheticProfile().replace(
    "2026-08-01T00:00:00.000Z",
    "2026-08-02T12:34:56.000Z",
  );

  assert.doesNotThrow(() => compareProfileText(current, baseline, "synthetic.conf"));
});

test("profile compatibility rejects every unapproved section and rule change", async (t) => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");
  const current = syntheticProfile();
  const mutations = [
    ["General", current.replace("ipv6 = true", "ipv6 = false")],
    ["Host", current.replace("localhost = 127.0.0.1", "localhost = ::1")],
    ["URL Rewrite", current.replace(" - reject", " - 302")],
    ["Proxy Group", current.replace("Synthetic = select,DIRECT", "Synthetic = select,REJECT")],
    ["Rule", current.replace("FINAL,Synthetic", "FINAL,DIRECT")],
    ["non-timestamp header value", current.replace("2026-08-01T00:00:00.000Z", "not-a-timestamp")],
    ["additional section", `${current}\n[MITM]\nenable = true\n`],
    ["section order", current.replace("[Host]", "[Host Renamed]")],
  ];

  for (const [name, mutation] of mutations) {
    await t.test(name, () => {
      assert.throws(() => compareProfileText(mutation, baseline, "synthetic.conf"));
    });
  }
});

test("profile compatibility requires the approved Advertising replacement", async () => {
  const { compareProfileText } = await import(comparatorUrl);
  const baseline = syntheticProfile("AdvertisingLite/AdvertisingLite.list");

  assert.throws(
    () => compareProfileText(baseline, baseline, "synthetic.conf"),
    /approved Advertising replacement is absent/,
  );
});

test("bundle compatibility ignores private IDs and rejects public contract changes", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const current = syntheticNodeBundle({
    privateId: "rebuilt-private-id",
    privateMetadataName: "_sr",
    realmOwnedArray: true,
  });
  const baseline = syntheticNodeBundle({ realmOwnedArray: true });

  await assert.doesNotReject(() => compareBundleSources("node", current, baseline, "synthetic-node.js"));

  const mutations = [
    ["exported global name", syntheticNodeBundle({ globalName: "RenamedNodeBundle" })],
    ["operator arity", syntheticNodeBundle({ wrapperParameters: "proxies" })],
    ["accepted arguments", syntheticNodeBundle({ rejectValidArguments: true })],
    ["rejected arguments", syntheticNodeBundle({ acceptUnknownArguments: true })],
    ["invalid output value", syntheticNodeBundle({ acceptInvalidOutput: true })],
    ["returned shape", syntheticNodeBundle({ returnObject: true })],
    ["public returned field", syntheticNodeBundle({ extraPublicField: true })],
  ];

  for (const [name, mutation] of mutations) {
    await t.test(name, async () => {
      await assert.rejects(() => compareBundleSources("node", mutation, baseline, "synthetic-node.js"));
    });
  }
});

test("profile bundle compatibility rejects profile-specific contract changes", async (t) => {
  const { compareBundleSources } = await import(comparatorUrl);
  const baseline = syntheticProfileBundle();

  await assert.doesNotReject(() => compareBundleSources("profile", baseline, baseline, "synthetic-profile.js"));

  const contractMutations = [
    ["exported global name", syntheticProfileBundle({ globalName: "RenamedProfileBundle" })],
    ["operator arity", syntheticProfileBundle({ wrapperParameters: "input" })],
    ["artifact request", syntheticProfileBundle({ artifactPlatform: "YAML" })],
    ["returned shape", syntheticProfileBundle({ extraPublicField: true })],
  ];
  for (const [name, mutation] of contractMutations) {
    await t.test(name, async () => {
      await assert.rejects(() => compareBundleSources("profile", mutation, baseline, "synthetic-profile.js"));
    });
  }

  for (const key of [
    "output", "type", "name", "subscriptionName", "platform", "dnsMode", "chinaDns",
    "globalDns", "blockMode", "quicMode", "ipv6Mode", "autoGroupMode", "clientChain",
  ]) {
    await t.test(`invalid ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptInvalidKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }

  for (const key of ["output", "type", "name", "subscriptionName", "platform"]) {
    await t.test(`missing ${key}`, async () => {
      await assert.rejects(() => compareBundleSources(
        "profile",
        syntheticProfileBundle({ acceptMissingKey: key }),
        baseline,
        "synthetic-profile.js",
      ));
    });
  }
});

test("compatibility verification refuses an unavailable baseline directory", async () => {
  const { verifyCompatibility } = await import(comparatorUrl);

  await assert.rejects(
    () => verifyCompatibility({
      baselineDir: new URL("fixtures/no-such-shadowrocket-baseline", import.meta.url).pathname,
      targetDir: new URL("..", import.meta.url).pathname,
    }),
    { message: "Shadowrocket baseline directory is unavailable" },
  );
});
