import assert from "node:assert/strict";
import test from "node:test";

import { buildGroups } from "../src/group-catalog.js";
import { normalizeNodes } from "../../../shared/nodes/normalize-nodes.js";
import { parsePrivatePolicy } from "../../../shared/policies/private-policy.js";
import { resolveUnifiedPolicy } from "../../../shared/policies/resolve-unified.js";
import { renderProfile } from "../src/render-profile.js";
import { validateProfile } from "../src/validate-profile.js";

const baseOptions = Object.freeze({
  output: "config",
  type: "collection",
  name: "shadowrocket-sources",
  subscriptionName: "Shadowrocket-Nodes",
  platform: "macos",
  dnsMode: "stable",
  chinaDns: "alidns",
  globalDns: "cloudflare",
  blockMode: "balanced",
  quicMode: "allow",
  ipv6Mode: "auto",
  autoGroupMode: "auto",
  clientChain: "off",
});

function inventory(count) {
  const continents = ["asiaPacific", "europe", "americas", "other"];
  const flags = ["🇯🇵", "🇩🇪", "🇺🇸", "🌐"];
  return Array.from({ length: count }, (_, index) => ({
    // Credentials and transport fields must not be rendered in a Profile.
    name: `${flags[index % flags.length]} node-${index}`,
    password: `TEST_ONLY_NOT_FOR_PROFILE_${index}`,
    _profile: {
      continent: continents[index % continents.length],
      flag: flags[index % flags.length],
      sourceKind: ["airport", "selfHosted", "realm"][index % 3],
      udp: index % 2 === 0,
      p2p: index % 3 === 0,
      entry: index === 0,
      chained: false,
    },
  }));
}

function structuralProfile({ groups = ["A = select,DIRECT"], rules = [], extraSections = [] } = {}) {
  return [
    "[General]",
    "x = y",
    "",
    "[Proxy Group]",
    ...groups,
    "",
    "[Rule]",
    ...rules,
    "GEOIP,CN,DIRECT",
    "FINAL,A",
    ...extraSections,
    "",
  ].join("\n");
}

test("renders a complete, valid macOS profile without node credentials", () => {
  const profile = renderProfile(baseOptions, inventory(25));

  assert.match(profile, /^# Generated by shadowrocket-profile\. Do not paste credentials into this file\.\n# platform=macos; node-count=25; node-refresh=21600; rule-refresh=86400\n/m);
  assert.ok(profile.includes("[General]"));
  assert.ok(profile.includes("[Proxy Group]"));
  assert.ok(profile.includes("[Rule]"));
  assert.equal(profile.includes("not-for-profile"), false);
  assert.equal(profile.endsWith("\n"), true);
  assert.equal(profile.includes("\n\n\n"), false);
  assert.deepEqual(validateProfile(profile), { valid: true, errors: [] });
});

test("uses policy.final as the default of the switchable leak group", () => {
  const nodes = inventory(25);
  const policy = parsePrivatePolicy(JSON.stringify({ schemaVersion: 2, targets: { final: "DIRECT" } }));
  const resolution = resolveUnifiedPolicy({ policy, client: "shadowrocket", allNodes: nodes, eligibleNodes: nodes });
  const profile = renderProfile(baseOptions, nodes, { policyResolution: resolution });

  assert.match(profile, /^漏网之鱼 = select,🚀 节点选择,DIRECT,REJECT,.*policy-select-name=DIRECT/mu);
  assert.match(profile, /^FINAL,漏网之鱼$/mu);
});

test("renders the current lightweight rules by default and permits GEOIP to resolve", () => {
  const profile = renderProfile(baseOptions, inventory(25));
  const rules = profile.slice(profile.indexOf("[Rule]")).split("\n").filter(Boolean);

  assert.match(profile, /current\/shadowrocket\/rules\/DomesticCore\.list/u);
  assert.doesNotMatch(profile, /\/(?:Advertising|Advertising_Domain|ChinaMax_Domain|ChinaMax|Game)\.list/u);
  assert.match(profile, /^RULE-SET,.*\/OverseasGame\.list,🌍 海外游戏,/mu);
  assert.equal(rules.at(-2), "GEOIP,CN,DIRECT");
  assert.equal(rules.at(-1), "FINAL,漏网之鱼");
});

test("rejects legacy publication channels", () => {
  assert.throws(
    () => renderProfile({ ...baseOptions, channel: "previous" }, inventory(25)),
    /channel|unsupported/iu,
  );
});

test("renders current full adblock from the separate optional publication", () => {
  const profile = renderProfile({
    ...baseOptions,
    channel: "current",
    adblockMode: "full",
  }, inventory(25));

  assert.match(profile, /current\/shadowrocket\/rules\/DomesticCore\.list/u);
  assert.match(profile, /current\/optional\/adblock-full\/shadowrocket\/rules\/Advertising\.list/u);
  assert.match(profile, /current\/optional\/adblock-full\/shadowrocket\/rules\/Advertising_Domain\.list/u);
  assert.doesNotMatch(profile, /current\/shadowrocket\/rules\/Advertising(?:_Domain)?\.list/u);
});

test("renders and validates exact named subscription sources", () => {
  const cases = [
    ["Nodes=Prod", "Nodes=Prod"],
    ["末尾反斜杠\\", "末尾反斜杠\\\\"],
    ["中文 内部 空格,普通=标点", "中文 内部 空格\\,普通=标点"],
    ["use=true", "use=true"],
  ];

  for (const [subscriptionName, encodedName] of cases) {
    const profile = renderProfile({ ...baseOptions, subscriptionName }, inventory(25));
    assert.equal(profile.includes(`,${encodedName},use=true,policy-regex-filter=`), true, subscriptionName);
    assert.deepEqual(validateProfile(profile), { valid: true, errors: [] }, subscriptionName);
  }
});

test("fails closed when client-chain inventory disagrees with Profile mode", () => {
  const eligibleEntry = {
    ...inventory(1)[0],
    name: "🇯🇵 [机场] eligible entry",
  };
  const chained = {
    name: "🔗 landing",
    _profile: {
      continent: "asiaPacific",
      sourceKind: "landing",
      udp: true,
      p2p: false,
      entry: false,
      chained: true,
    },
  };

  assert.throws(
    () => renderProfile(baseOptions, [eligibleEntry, chained]),
    /clientChain=off.*chained/i,
  );
  assert.throws(
    () => renderProfile({ ...baseOptions, clientChain: "on" }, [chained]),
    /clientChain=on.*eligible.*entry/i,
  );
  const valid = renderProfile(
    { ...baseOptions, clientChain: "on" },
    [eligibleEntry, chained],
  );
  assert.deepEqual(validateProfile(valid), { valid: true, errors: [] });

  const homepageProxy = structuralProfile({
    groups: ["A = select,PROXY,Nodes,use=true,policy-regex-filter=^.+$"],
  });
  assert.deepEqual(validateProfile(homepageProxy), { valid: true, errors: [] });
  const missingDynamicSource = homepageProxy.replace(",Nodes,use=true", "");
  assert.equal(validateProfile(missingDynamicSource).valid, false);
  assert.match(validateProfile(missingDynamicSource).errors.join("\n"), /include-all-proxies/i);
});

test("client-chain Profiles never serialize raw normalized node names or transport details", () => {
  const credential = ["TEST_ONLY", "PROFILE", "CREDENTIAL"].join("_");
  const endpoint = "private-node.example.invalid";
  const port = 45678;
  const eligible = {
    name: `JP ${endpoint} ${port} ${credential} [已有链]`,
    type: "ss",
    server: endpoint,
    port,
    cipher: "aes-128-gcm",
    password: credential,
    udp: true,
    _subName: "[机场] private",
  };
  const preChained = {
    ...eligible,
    name: "JP pre-existing chain",
    password: "TEST_ONLY_PRECHAINED_PRIVATE",
    chain: "existing-hop",
  };
  const landing = {
    ...eligible,
    name: "JP private landing",
    password: "TEST_ONLY_PRIVATE_LANDING",
    _subName: "[落地] private",
  };
  const { nodes } = normalizeNodes([eligible, preChained, landing], { clientChain: "on" });
  const profile = renderProfile({ ...baseOptions, clientChain: "on" }, nodes);
  const entryFilter = buildGroups({ ...baseOptions, clientChain: "on" }, nodes)
    .find((group) => group.name === "🔗 入口节点").filter;
  const eligibleNode = nodes.find((node) => node._profile.entry);
  const restrictedNode = nodes.find((node) => node.chain === "existing-hop");

  for (const privateValue of [
    eligible.name,
    preChained.name,
    landing.name,
    eligibleNode.name,
    restrictedNode.name,
    endpoint,
    `${port} ${credential}`,
    credential,
  ]) assert.equal(profile.includes(privateValue), false, privateValue);
  assert.equal(new RegExp(entryFilter).test(eligibleNode.name), true);
  assert.equal(new RegExp(entryFilter).test(restrictedNode.name), false);
  assert.match(restrictedNode.name, /｜机场·链·U$/);
  assert.match(profile, /policy-regex-filter=\^\(\?!🔗 \)\(\?!\.\*·链\)/);
  assert.deepEqual(validateProfile(profile), { valid: true, errors: [] });
});

test("renders valid profiles for the platform and routing option matrix", () => {
  for (const platform of ["macos", "iphone", "ipad", "appletv"]) {
    for (const blockMode of ["off", "security", "balanced", "strict"]) {
      for (const quicMode of ["allow", "proxy-block", "all-block"]) {
        for (const ipv6Mode of ["auto", "ipv4-only"]) {
          const profile = renderProfile({ ...baseOptions, platform, blockMode, quicMode, ipv6Mode }, inventory(120));
          assert.deepEqual(validateProfile(profile), { valid: true, errors: [] }, `${platform}/${blockMode}/${quicMode}/${ipv6Mode}`);
        }
      }
    }
  }
});

test("validates group graph and routing-policy structure", () => {
  const valid = [
    "[General]",
    "x = y",
    "",
    "[Proxy Group]",
    "A = select,DIRECT",
    "B = select,A",
    "",
    "[Rule]",
    "RULE-SET,https://example.invalid/list,B",
    "AND,((PROTOCOL,UDP),(RULE-SET,https://example.invalid/game)),A",
    "GEOIP,CN,DIRECT",
    "FINAL,B",
    "",
  ].join("\n");
  assert.deepEqual(validateProfile(valid), { valid: true, errors: [] });

  const duplicate = valid.replace("B = select,A", "A = select,A");
  assert.equal(validateProfile(duplicate).valid, false);
  assert.match(validateProfile(duplicate).errors.join("\n"), /duplicate group/i);

  const duplicateSection = valid.replace("[Rule]", "[Rule]\n# duplicate headers must remain visible to validation\n[Rule]");
  assert.equal(validateProfile(duplicateSection).valid, false);
  assert.match(validateProfile(duplicateSection).errors.join("\n"), /duplicate required section/i);

  const missing = valid.replace("B = select,A", "B = select,Missing");
  assert.equal(validateProfile(missing).valid, false);
  assert.match(validateProfile(missing).errors.join("\n"), /missing group/i);

  const cyclic = valid.replace("A = select,DIRECT\nB = select,A", "A = select,B\nB = select,A");
  assert.equal(validateProfile(cyclic).valid, false);
  assert.match(validateProfile(cyclic).errors.join("\n"), /cycle/i);

  const geoipAfterFinal = valid.replace("GEOIP,CN,DIRECT\nFINAL,B", "FINAL,B\nGEOIP,CN,DIRECT");
  assert.equal(validateProfile(geoipAfterFinal).valid, false);
  assert.match(validateProfile(geoipAfterFinal).errors.join("\n"), /GEOIP.*FINAL/i);

  const escapedComma = valid.replace("A = select,DIRECT", "node\\,with\\,comma = random,DIRECT\nA = select,node\\,with\\,comma,Nodes,use=true");
  assert.deepEqual(validateProfile(escapedComma), { valid: true, errors: [] });

  const random = valid.replace("A = select,DIRECT", "A = random,DIRECT");
  assert.deepEqual(validateProfile(random), { valid: true, errors: [] });

  const nonEmojiReference = valid.replace("A = select,DIRECT", "source = random,DIRECT\nA = select,source");
  assert.deepEqual(validateProfile(nonEmojiReference), { valid: true, errors: [] });

  const missingSubscriptionItem = valid.replace("A = select,DIRECT", "A = select,Missing,Nodes,use=true");
  assert.equal(validateProfile(missingSubscriptionItem).valid, false);
  assert.match(validateProfile(missingSubscriptionItem).errors.join("\n"), /missing group/i);

  const danglingNormalizedNode = valid.replace("A = select,DIRECT", "A = select,🇯🇵 [机场] definitely-not-in-subscription");
  assert.equal(validateProfile(danglingNormalizedNode).valid, false);
  assert.match(validateProfile(danglingNormalizedNode).errors.join("\n"), /missing group/i);

  const escapedAndPolicy = valid
    .replace("A = select,DIRECT", "A\\,B = select,DIRECT")
    .replace("B = select,A", "C = select,A\\,B")
    .replace("RULE-SET,https://example.invalid/list,B", "RULE-SET,https://example.invalid/list,C")
    .replace(")),A", ")),A\\,B")
    .replace("FINAL,B", "FINAL,C");
  assert.deepEqual(validateProfile(escapedAndPolicy), { valid: true, errors: [] });

  const missingEscapedAndPolicy = escapedAndPolicy.replace("A\\,B\nGEOIP", "Missing\\,C\nGEOIP");
  assert.equal(validateProfile(missingEscapedAndPolicy).valid, false);
  assert.match(validateProfile(missingEscapedAndPolicy).errors.join("\n"), /AND.*missing group/i);

  const missingAndPolicy = valid.replace(/,A\nGEOIP/, "\nGEOIP");
  assert.equal(validateProfile(missingAndPolicy).valid, false);
  assert.match(validateProfile(missingAndPolicy).errors.join("\n"), /AND.*policy/i);
  assert.deepEqual(validateProfile(null), { valid: false, errors: ["Profile must be a string"] });
});

test("rejects malformed sections, group declarations, and all rule policy forms", () => {
  const supportedRules = [
    "DOMAIN,example.invalid,A",
    "DOMAIN-SUFFIX,example.invalid,A",
    "DOMAIN-KEYWORD,example,A",
    "DOMAIN-WILDCARD,a?.example.invalid,A",
    "IP-CIDR,192.0.2.0/24,A,no-resolve",
    "IP-CIDR6,2001:db8::/32,A,no-resolve",
    "SRC-IP-CIDR,198.51.100.0/24,A,no-resolve",
    "DST-PORT,443-8443,A",
    "DEST-PORT,443,A",
    "USER-AGENT,Example,A",
    "PROCESS-NAME,Example,A",
    "URL-REGEX,^https://example\\.invalid,A",
    "IP-ASN,13335,A",
    "GEOIP,US,A",
    "RULE-SET,https://example.invalid/list,A,update-interval=86400",
    "DOMAIN-SET,https://example.invalid/domains,A,update-interval=86400",
    "OR,((PROTOCOL,TCP),(PROTOCOL,UDP)),A",
    "NOT,(PROTOCOL,UDP),A",
    "AND,((PROTOCOL,UDP),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://example.invalid/nested.list),(DST-PORT,443)),A",
    "AND,((RULE-SET,http://192.0.2.10:8080/list),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://[2001:db8::1]:8443/path),(DST-PORT,443)),A",
  ];
  assert.deepEqual(validateProfile(structuralProfile({ rules: supportedRules })), { valid: true, errors: [] });

  const missingGenericPolicy = structuralProfile({ rules: ["DOMAIN-SUFFIX,example.invalid,Missing"] });
  assert.equal(validateProfile(missingGenericPolicy).valid, false);
  assert.match(validateProfile(missingGenericPolicy).errors.join("\n"), /DOMAIN-SUFFIX.*missing group/i);

  for (const rule of [
    "DOMAIN-SUFFIX,example.invalid",
    "IP-CIDR,not-a-cidr,A",
    "DOMAIN-SUFFIX,..bad..,A",
    "IP-ASN,ASbad,A",
    "DOMAIN,*.example.com,A",
    "DOMAIN-SUFFIX,a?.example.com,A",
    "DOMAIN-WILDCARD,..bad..,A",
    "SRC-IP-CIDR,not-a-cidr,A,no-resolve",
    "DST-PORT,8443-443,A",
    "AND,((PROTOCOL,UDP),(DST-PORT,8443-443)),A",
    "AND,((PROTOCOL,BOGUS),(DST-PORT,443)),A",
    "AND,((UNKNOWN,value),(DST-PORT,443)),A",
    "AND,((RULE-SET,not-a-url),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://:),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://example.com:bad/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://[::1/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://..),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://-bad.example/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://bad-.example/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://2001:db8::1/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://example.com:0/x),(DST-PORT,443)),A",
    "AND,((RULE-SET,https://example.com:65536/x),(DST-PORT,443)),A",
    "AND,((PROTOCOL,UDP,EXTRA),(DST-PORT,443)),A",
    "UNKNOWN,example.invalid,A",
    "AND,((PROTOCOL,UDP),(RULE-SET,https://example.invalid/game),A",
    "NOT,((PROTOCOL,UDP),(RULE-SET,https://example.invalid/game)),A",
  ]) {
    assert.equal(validateProfile(structuralProfile({ rules: [rule] })).valid, false, rule);
  }

  for (const group of ["A = select", "A = select,use=true"]) {
    assert.equal(validateProfile(structuralProfile({ groups: [group] })).valid, false, group);
    assert.match(validateProfile(structuralProfile({ groups: [group] })).errors.join("\n"), /selectable item|subscription source/i);
  }

  const unescapedGroupName = structuralProfile({ groups: ["A,B = select,DIRECT"] });
  assert.equal(validateProfile(unescapedGroupName).valid, false);
  assert.match(validateProfile(unescapedGroupName).errors.join("\n"), /invalid proxy group/i);
  assert.deepEqual(validateProfile(structuralProfile({
    groups: ["A = select,DIRECT", "A\\,B = select,DIRECT"],
    rules: ["DOMAIN,example.invalid,A\\,B"],
  })), { valid: true, errors: [] });

  const unknownSection = structuralProfile({ extraSections: ["[Extra]"] });
  assert.equal(validateProfile(unknownSection).valid, false);
  assert.match(validateProfile(unknownSection).errors.join("\n"), /unrecognized section/i);

  const duplicateUnknown = structuralProfile({ extraSections: ["[Extra]", "[Extra]"] });
  assert.equal(validateProfile(duplicateUnknown).valid, false);
  assert.match(validateProfile(duplicateUnknown).errors.join("\n"), /duplicate section/i);
});
