import { nodeMetadata } from "../../../shared/contracts.js";
import { parseSurgeOptions, isParsedSurgeOptions } from "./options.js";
import { renderSurgeProxy } from "./render-node.js";
import { renderSurgeGroups } from "./render-groups.js";
import { renderSurgeRules } from "./render-rules.js";
import { validateSurgeProfile } from "./validate-profile.js";

const LOCAL_SKIP_PROXY = Object.freeze([
  "localhost", "*.local", "*.lan", "*.home.arpa", "10.0.0.0/8", "100.64.0.0/10",
  "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "224.0.0.0/4",
  "::1/128", "fc00::/7", "fe80::/10", "ff00::/8",
]);
function generalSettings(options) {
  const chinaDns = { alidns: "223.5.5.5", dnspod: "119.29.29.29", system: "system" }[options.chinaDns];
  return [
    "loglevel = notify",
    `ipv6 = ${options.ipv6Mode === "auto" ? "true" : "false"}`,
    `dns-server = ${chinaDns}`,
    `skip-proxy = ${LOCAL_SKIP_PROXY.join(",")}`,
    "exclude-simple-hostnames = true",
    "internet-test-url = http://www.gstatic.com/generate_204",
    "proxy-test-url = http://www.gstatic.com/generate_204",
    `test-timeout = ${options.platform === "macos" ? 5 : 7}`,
    "suppress-warnings = true",
  ];
}

export function renderSurgeProfile(rawOptions, nodes, { ruleBaseUrl } = {}) {
  const options = isParsedSurgeOptions(rawOptions) ? rawOptions : parseSurgeOptions(rawOptions);
  const inventory = Array.isArray(nodes) ? nodes : [];
  if (inventory.length === 0) throw new Error("Surge refuses an empty node inventory");
  for (const node of inventory) nodeMetadata(node);
  const hasRemotePolicy = Boolean(options.proxyPolicyUrl);
  const proxyLines = hasRemotePolicy
    ? "# Nodes are loaded by the hidden Surge remote policy pool."
    : inventory.map(renderSurgeProxy).join("\n");
  const profile = [
    "# Generated by apple-proxy-profiles. Private Sub-Store output.",
    `[General]\n${generalSettings(options).join("\n")}`,
    `[Proxy]\n${proxyLines}`,
    `[Proxy Group]\n${renderSurgeGroups(options, inventory).join("\n")}`,
    `[Rule]\n${renderSurgeRules({ ruleBaseUrl, adblockMode: options.adblockMode }).join("\n")}`,
  ].join("\n\n") + "\n";
  const validation = validateSurgeProfile(profile);
  if (!validation.valid) throw new Error(`Generated Surge profile failed validation: ${validation.errors.join(",")}`);
  return profile;
}
